# define environment via docker container
# image: add something 

# define stages
stages:
    - test
    #- build
	#- deploy
	#-lint  # create stage to check codestyle with pylint?
    
# define task which should execute before each jobs
before_script:
    # add something

# define jobs
test:
    stage: test
    image: python:3.8
    script:
    #- echo "This job test something"
    - pytest tests --disable-warnings
    

	
    

