# define stages
stages:
    - test
    - docker
    #- build
    #- deploy
    #- lint  # create stage to check codestyle with pylint?
    
# define task which should execute before each jobs
before_script:
    # add something

# testing changes 
test:
    stage: test
    image: 
      name: registry.gitlab.cc-asp.fraunhofer.de/dave/dave
      entrypoint: [""]
    tags:
    - asprunner
    script:
    - pytest dave/tests --disable-warnings
    only:
    - master
    - develop

# build release docker container from master branch
# push to gwdg
# build_release_container:
#   stage: docker
#   image:
#     name: gcr.io/kaniko-project/executor:debug
#     entrypoint: [""]
#   tags:
#   - asprunner
#   script:
#     - mkdir -p /kaniko/.docker
#     - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$CI_REGISTRY_TOKEN\"}, \"registry.gitlab.cc-asp.fraunhofer.de:4567\":{\"auth\":\"$CI_CC_TOKEN\"}}}" > /kaniko/.docker/config.json
#     - /kaniko/executor --context dir:///$CI_PROJECT_DIR/ --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY/spinai_ui:release --insecure --skip-tls-verify --insecure-pull --cleanup
#   only:
#     - master

# build develop docker container from develop branch (push to git zv)
build_develop_container:
  stage: docker
  when: manual
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  tags:
    - asprunner
  script:
    - mkdir -p /kaniko/.docker
    - echo "$CI_REGISTRY"
    - echo "$CI_REGISTRY_TOKEN_USER"
    - echo "$CI_REGISTRY_TOKEN_PASSWORD"
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_TOKEN_USER\",\"password\":\"$CI_REGISTRY_TOKEN_PASSWORD\"}}}" > /kaniko/.docker/config.json
    #- echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$CI_REGISTRY_TOKEN\"}, \"registry.gitlab.cc-asp.fraunhofer.de/dave/dave\":{\"auth\":\"$CI_REGISTRY_TOKEN_PW\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context dir:///$CI_PROJECT_DIR/ --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY/dave/dave:latest --insecure --skip-tls-verify --insecure-pull --cleanup
  only:
    - develop