# define environment via docker container


# define stages
stages:
    - test
    - docker
    #- build
    #- deploy
    #- lint  # create stage to check codestyle with pylint?
    
# define task which should execute before each jobs
before_script:
    # add something

# testing changes 
test:
    stage: test
    image: 
      name: registry.gitlab.cc-asp.fraunhofer.de/dave/dave
      entrypoint: [""]
    tags:
    - asprunner
    script:
    - pytest tests --disable-warnings
    only:
    - master
    - develop
