name: base
channels:
  - conda-forge
dependencies:
  - python=3.11.6
  - shapely
  - geopandas
  - matplotlib
  - geopy
  - contextily  # schauen ob man das raus bekommt
  - fastapi
  - uvicorn
  - pytest
  - pytest-cov
  - pytest-xdist
  - pymongo
  - openpyxl
  - xmlschema
  - lxml
  - python-keycloak
  - authlib
  - pytables
  - pyopenssl
  - rasterio
  - tqdm
  - owslib
  - numba == 0.57.1
  - pip
  - pip:
    - pandapower
    - pandapipes
    - dave_client-0.0.0-py3-none-any.whl
