name: dave_core
channels:
  - conda-forge
dependencies:
  - python=3.12.7
  - shapely
  - geopandas
  - matplotlib
  - geopy
  - fiona
  - networkx
  - contextily
  - pytest
  - pytest-cov
  - pytest-xdist
  - openpyxl
  - xmlschema
  - lxml
  - tqdm
  - tables
  - defusedxml
  - dask_geopandas
  - pip
  - pip:
      - pandapower
      - pandapipes
