name: dave
channels:
  - conda-forge
dependencies:
  - python=3.11.6
  - shapely
  - geopandas
  - matplotlib
  - geopy
  - contextily
  - fastapi
  - uvicorn
  - pytest
  - pytest-cov
  - pytest-xdist
  - pymongo
  - openpyxl
  - xmlschema
  - lxml
  - python-keycloak
  - authlib
  - pytables
  - rasterio
  - tqdm
  - owslib
  - pip
  - pip:
      - pandapower
      - pandapipes