[build-system]
requires = ["build", "wheel", "setuptools"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100

[tool.coverage.run]
omit = ["tests/*", 
"*/__init__.py"]

[tool.coverage.report]
exclude_lines = [
  "pragma: no cover",
  "if 0:",
  "if __name__ == .__main__.:",
]
omit = ["tests/*", 
"*/__init__.py"]

#[tool.coverage.html]
#directory = coverage

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3

